config/routes.rb
Rails.application.routes.draw do
  root 'admin#index'

  resources :orders, only: [:index, :show, :update], param: :number
 
  resources :reports, only: :index do
    collection do
      get :coupon_users
      get :sales_by_product
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  validates_presence_of   :address1, :city, :state, :user_id
  validates_uniqueness_of :user_id

  validates :zipcode,
            format: {
              with: /\A\d{5}\z/,
              message: "not valid. Please enter your 5 digit zipcode"
            }, presence: true

  belongs_to :user

  has_many   :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  validates_presence_of :name

  validates   :amount,
              presence: true,
              numericality: {
                greater_than_or_equal_to: 0
              },
              format: {
                with: /\A-?\d+\.?\d{0,2}\z/,
                message: 'only accepts 2 decimal places.'
              }

  has_many :order_items,
           as: :source

  has_many :orders, through: :order_items
  has_many :users, through: :orders
end

app/models/order.rb
class Order < ApplicationRecord
  BUILDING = "building"
  ARRIVED = "arrived"
  CANCELED = "canceled"
  STATES = [BUILDING, ARRIVED, CANCELED].freeze

  validates_presence_of :user_id, :state

  validates   :total,
              presence: true,
              format: {
                with: /\A-?\d+\.?\d{0,2}\z/,
                message: 'only accepts 2 decimal places.'
              }

  belongs_to :user
  belongs_to :address

  has_many :order_items
  has_many :payments

  scope :arrived, -> { where(state: 'arrived') }
  scope :by_coupon, ->(coupon_id) do
    joins(:order_items)
      .where(order_items: {source_type: "Coupon", source_id: coupon_id })
      .group(:id)
  end

  scope :arrived_between, ->(start_date, end_date) { where(arrived_at: start_date..end_date)}

  def to_param
    number
  end

  def cancel
    order_items.update_all(state: 'returned')
    payments.update_all(state: 'refunded')
    self.update(state: CANCELED)
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  SOLD = "sold"
  RETURNED = "returned"
  STATES = [SOLD, RETURNED].freeze
  validates_presence_of :order_id, :source_id, :source_type, :price

  validates :state,
            absence: true,
            if: -> { source_type != Product.name }

  validates :state,
            allow_nil: false,
            inclusion: STATES,
            if: -> { source_type == Product.name && order.building_at.present? }

  validates :quantity,
            presence: true,
            numericality: {
              greater_than: 0
            }

  belongs_to :order
  belongs_to :source,
             polymorphic: true
end

app/models/payment.rb
class Payment < ApplicationRecord
  COMPLETED = "completed"
  REFUNDED = "refunded"
  STATES = [COMPLETED, REFUNDED].freeze

  CREDIT_CARD = "CreditCard"
  STORE_CREDIT = "StoreCredit"
  PAYMENT_TYPES = [CREDIT_CARD, STORE_CREDIT].freeze

  validates_presence_of :order_id, :state, :payment_type

  validates   :amount,
              presence: true,
              format: {
                with: /\A-?\d+\.?\d{0,2}\z/,
                message: 'only accepts 2 decimal places.'
              }

  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  validates_presence_of :name

  validates   :sku,
              presence: true,
              uniqueness: true

  validates   :msrp,
              presence: true,
              numericality: {
                greater_than_or_equal_to: 0
              },
              format: {
                with: /\A-?\d+\.?\d{0,2}\z/,
                message: 'only accepts 2 decimal places.'
              }

  validates   :cost,
              presence: true,
              numericality: {
                greater_than_or_equal_to: 0
              },
              format: {
                with: /\A-?\d+\.?\d{0,2}\z/,
                message: 'only accepts 2 decimal places.'
              }

  has_many :order_items,
           as: :source

  scope :by_orders, ->(order_ids) do
    joins(:order_items)
      .where(order_items: {order_id: order_ids })
      .group(:id)
  end
end

app/models/tax.rb
class Tax < ApplicationRecord
  validates :name,
            presence: true

  validates :rate,
            presence: true,
            numericality: {
              greater_than_or_equal_to: 0,
              less_than_or_equal_to: 1
            },
            format: {
              with: /\A-?\d+\.?\d{0,3}\z/,
              message: 'only accepts 3 decimal places.'
            }

  has_many :order_items,
           as: :source
end

app/models/user.rb
class User < ApplicationRecord

  validates :name,
            presence: true

  validates :email,
            presence: true,
            uniqueness: true

  has_many :orders
  has_many :addresses

  def arrived_coupon_orders(coupon_id)
    orders.arrived.by_coupon(coupon_id)
  end

  def arrived_orders_count(coupon_id)
    arrived_coupon_orders(coupon_id).pluck('count(*)').first || 0
  end

   def arrived_orders_revenue(coupon_id)
    arrived_coupon_orders(coupon_id).pluck('sum(orders.total)').first || 0
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :find_order!, only: [:show, :update]

  SEARCHABLE_FIELDS = ['orders.number','orders.state', 'users.email'].freeze

  def index
    if params[:query].present?
      @orders ||= Order.joins([:user, :address]).where("#{query_field} LIKE ?", "%#{params[:query]}%").paginate(page: params[:page])
    else
      @orders ||= Order.joins([:user, :address]).paginate(page: params[:page])
    end
  end

  def show
  end

  def update
    @order.cancel
    redirect_to  action: :show
  end

  private
  def find_order!
    @order = Order.find_by!(number: params[:number])
  end

  def query_field
    if SEARCHABLE_FIELDS.include? params[:query_field]
      params[:query_field]
    else
      nil
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
  end

  def coupon_users
    @coupon = params[:coupon_id] && Coupon.find(params[:coupon_id])
  end

  def sales_by_product
    if params[:commit].present?
      order_ids = Order.arrived_between(params[:start_date], params[:end_date]).pluck(:id)
      @products = Product.by_orders(order_ids).select('name, sum(products.cost) as revenue, count(*) as count')
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def query_field_params(query_field)
    options_for_select([
      ['Order number', 'orders.number'],
      ['Order state', 'orders.state'],
      ['Email', 'users.email'],
      ['Username', 'users.name'],
      ['State', 'addresses.state'],
      ['Ciry', 'addresses.city']
    ],
    query_field)
  end
end

app/helpers/report_helper.rb
module ReportHelper
  def coupon_options(coupon_id)
    options_for_select Coupon.all.map{ |coupon| [coupon.name, coupon.id]}, coupon_id
  end
end

app/views/layouts/application.haml
!!!
%html
  %head
    %title CodeChallenge

    = csrf_meta_tags
    = csp_meta_tag
    = tag "meta", "http-equiv" => "Accept-CH", content: "DPR, Viewport-Width, Width"
    = tag 'meta', {"http-equiv" => "Accept-CH", content: "width=device-width, initial-scale=1.0, user-scalable=no", name: "viewport", id: "vp"}, true
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    %nav.navbar.navbar-default.navbar-fixed-top
      .container-fluid
        .navbar-header
          =link_to root_path, class: "navbar-brand" do
            =image_tag "logo"

        .collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li{class: current_page?(controller: "orders") ? 'active' : ''}
              =link_to orders_path do
                Orders

            %li{class: current_page?(controller: "reports") ? 'active' : ''}
              =link_to reports_path do
                Reports

    .container-fluid{role: "main"}
      = yield

app/views/orders/index.haml
= form_tag orders_path, method: :get do
  .col-xs-2
    = select_tag :query_field, query_field_params(params[:query_field]), class: "form-control"
  .col-xs-8
    = text_field_tag :query, params[:query], type: "text", class: "form-control"
  .col-xs-2
    = submit_tag "submit", method: :get, class: "btn btn-primary"

%table.table
  %thead
    %th Order Number
    %th Order State
    %th Total
    %th User Email
    %th User Name
    %th State
    %th City
  %tbody
  - @orders.each do |order|
    %tr
      %td= link_to order.number, order_path(order.number)
      %td= order.state
      %td= order.total
      %td= order.user.email
      %td= order.user.name
      %td= order.address.state
      %td= order.address.city
= will_paginate @orders

app/views/orders/show.haml
%h2 Order #{@order.number} #{@order.state}
-if @order.state != 'canceled'
  = form_tag order_path, method: :put do
    = submit_tag "cancel", class: "btn btn-primary"

%p Primary address #{@order.address.address1}
- if @order.address.address2
  %p Secondary address #{@order.address.address2}

User: #{@order.user.email}

%h3 Payments
- @order.payments.each do |payment|
  Id: #{payment.id} #{payment.state}. Payment amount #{payment.amount}

%h3 Items
%table.table
  %thead
    %th Name
    %th Quantity
    %th Price
    %th State
  %tbody
    - @order.order_items.each do |item|
      %tr
        %td= item.source.name
        %td= item.quantity
        %td= item.price
        %td= item.state

app/views/reports/coupon_users.haml
= form_tag coupon_users_reports_path, method: :get, class: "row" do
  .col-sm-4
    = select_tag :coupon_id, coupon_options(params[:coupon_id]), class: "form-control"
  .col-xs-2
    = submit_tag "submit", method: :get, class: "btn btn-primary"

- if @coupon
  %table.table
    %thead
      %th User Email
      %th Arrived orders count
      %th Total revenue
    %tbody
      - @coupon.users.each do |user|
        %tr
          %td= user.email
          %td= user.arrived_orders_count(@coupon.id)
          %td= user.arrived_orders_revenue(@coupon.id)

app/views/reports/index.haml
=link_to "Coupon Users", coupon_users_reports_path
=link_to "Sales By Product", sales_by_product_reports_path

app/views/reports/sales_by_product.haml
= form_tag sales_by_product_reports_path, method: :get, class: "row" do
  .col-sm-4
    = label_tag 'Start date'
    = text_field_tag :start_date, params[:start_date], class: "datepicker"
  .col-sm-4
    = label_tag 'End date'
    = text_field_tag :end_date, params[:end_date], class: "datepicker"
  .col-xs-2
    = submit_tag "submit", method: :get, class: "btn btn-primary"
- if @products
  %table.table
    %thead
      %th Product
      %th Sold count
      %th Revenue
    %tbody
      - @products.each do |product|
        %tr
          %td= product.name
          %td= product.count
          %td= product.revenue